<!DOCTYPE html>
<html>
<head>
    <title>Salary Slip #{{ $salary->id }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        body {
            background-color: #f8fafc;
            color: #0f172a;
        }

        @media print {
            body {
                print-color-adjust: exact !important;
                -webkit-print-color-adjust: exact !important;
                background-color: #ffffff;
                margin: 0;
                padding: 0;
            }

            @page {
                size: auto;
                margin: 8mm;
            }
        }
    </style>
</head>
<body class="py-8">
<div class="mx-auto w-full max-w-4xl rounded-xl border border-slate-200 bg-white p-8 shadow-sm">
    <div class="mb-8 flex items-start justify-between border-b pb-6">
        <div>
            <p class="text-xs uppercase tracking-[0.25em] text-slate-500">Salary Slip</p>
            <h1 class="mt-2 text-3xl font-black uppercase tracking-wide">{{ $salary->employee?->full_name }}</h1>
            <p class="mt-1 text-sm text-slate-600">
                {{ $salary->salary_month?->format('F Y') }} | #{{ $salary->id }}
            </p>
        </div>

        <div class="text-right text-sm text-slate-600">
            <p class="font-semibold">{{ $salary->company?->name }}</p>
            <p>Status: {{ ucfirst($salary->status) }}</p>
            <p>Printed: {{ now()->format('Y-m-d H:i') }}</p>
        </div>
    </div>

    <div class="grid grid-cols-2 gap-8 text-sm">
        <div class="space-y-3 rounded-lg border border-slate-200 p-4">
            <p><span class="font-semibold">Base Salary:</span> {{ number_format((float) $salary->base_salary, 2) }}</p>
            <p><span class="font-semibold">Bonus:</span> {{ number_format((float) $salary->bonus, 2) }}</p>
            <p><span class="font-semibold">Deduction:</span> {{ number_format((float) $salary->deduction, 2) }}</p>
            <p class="pt-3 text-base font-bold"><span>Net Salary:</span> {{ number_format((float) $salary->net_salary, 2) }}</p>
        </div>

        <div class="space-y-3 rounded-lg border border-slate-200 p-4">
            <p><span class="font-semibold">Paid Days:</span> {{ number_format((float) $salary->paid_days, 2) }}</p>
            <p><span class="font-semibold">Absent Days:</span> {{ number_format((float) $salary->absent_days, 2) }}</p>
            <p><span class="font-semibold">Week Off Days:</span> {{ number_format((float) $salary->week_off_days, 2) }}</p>
            <p><span class="font-semibold">Paid At:</span> {{ $salary->paid_at?->format('Y-m-d H:i') ?: '-' }}</p>
        </div>
    </div>

    <div class="mt-8 rounded-lg border border-slate-200 p-4">
        <p class="mb-2 text-xs font-semibold uppercase tracking-widest text-slate-500">Notes</p>
        <p class="text-sm text-slate-700">{{ $salary->notes ?: 'No notes provided.' }}</p>
    </div>

    <div class="mt-10 flex items-end justify-between text-xs text-slate-500">
        <p>Generated by {{ config('app.name') }}</p>
        <button onclick="window.print()" class="rounded-md bg-slate-900 px-4 py-2 text-white print:hidden">Print</button>
    </div>
</div>
</body>
</html>
